# Generated by Django 5.2 on 2026-01-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('height', models.IntegerField(blank=True, default=0)),
                ('width', models.IntegerField(blank=True, default=0)),
                ('photo', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
