# Generated by Django 5.2 on 2026-01-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last Edited'),
        ),
    ]
