# Generated by Django 5.2 on 2026-01-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0002_pot_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last edited'),
        ),
    ]
