# Generated by Django 5.2 on 2026-01-18 22:08

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0003_alter_pot_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to='products/'),
        ),
    ]
